### PR TITLE
Change precedence of this style guide

### PR DESCRIPTION
**Pull request by twyatt**
Bumps this guide (https://github.com/JuulLabs-OSS/kotlin-guides) to the first position (from last) on the list of precedence of guides to follow.

### CODE REVIEW

**Comment by ebabel** [comment]
You want google and jetbrains to have precedence over our style?

**Comment by twyatt** [comment]
> You want google and jetbrains to have precedence over our style?

I want our guide to have precedence **over** JetBrains and Google, hence this PR.

**Review by ebabel — APPROVED** [review]

**Comment by nachtien** [comment]
Do we need to make changes to our style config in Android Studio?

**Review by nachtien — APPROVED** [review]

**Comment by twyatt** [comment]
> Do we need to make changes to our style config in Android Studio?

I don't think any of the rules of this guide are enforced by our codestyles, so no changes there should be necessary; good thinking though!

**Pull request merged**
